version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: postgres_tarefakanban
    restart: always
    ports:
      - "5444:5432"
    environment:
      POSTGRES_DB: tarefakanban_db       # Nome do banco de dados
      POSTGRES_USER: tarefa_user         # Nome do usuário
      POSTGRES_PASSWORD: tarefa_pass     # Senha do usuário
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
